
project_id = "bjzvlatqgrqaefnwihjj"

[functions.transcribe-video]
verify_jwt = true

[functions.generate-slides]
verify_jwt = true

[functions.extract-frames]
verify_jwt = true

[functions.usage-stats-service]
verify_jwt = true

[functions.init-storage]
verify_jwt = true

[functions.sync-storage-usage]
verify_jwt = true
