// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjzvlatqgrqaefnwihjj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqenZsYXRxZ3JxYWVmbndpaGpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MDcxODUsImV4cCI6MjA2MjE4MzE4NX0.QfaKVj83pSqm7cd8IEuDkQ_LSFROOMBY_jhaEvUxx5g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);